[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "cd apps/serp-dashboard && npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
node-version = "18"